---
- hosts: webservers
  become: yes
  tasks:
  - name: my host name 
    command: hostname -f
    register: myresult

  - name: disply the above task result
    debug:
      msg: "{{myresult}}"

  - name: install git
    apt:
      name: git
    when:  myresult.stderr ==""

  - name: install tree
    apt: 
      name: tree"
    when: myresult.stderr !=""