---
- hosts: webservers
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
    notify: restartwebservers
  

  - name: copy index.j2  file into  nodes
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restartwebservers
  
  handlers:
  - name: restartwebservers
    service:
      name: apache2
      state: restarted